<?php
    require_once '../vendor/autoload.php';
    require_once '../backend/db/connection.php';

    $google_auth = new Sonata\GoogleAuthenticator\GoogleAuthenticator();

    session_start();
    $user_id = $_SESSION['id'] ?? null;
    $username = null;

    // getting the user register
    $query = 'SELECT id, name, 2fa_secret_code FROM users WHERE id="' . $user_id . '";';
    $result = mysqli_query($conn, $query);

    $secret = null;
    $generate_qr = false;

    if($result) {
        if(mysqli_num_rows($result) > 0) {
            $row = mysqli_fetch_assoc($result);
            $username = $row['name'];

            /* verify if the secret key already generated, if ok,
             * receive a input of the code generated by google authenticator app
             */
            if ($row['2fa_secret_code'] != null) {
                $secret = $row['2fa_secret_code'];
            } else {
                $secret = $google_auth->generateSecret();
                $generate_qr = true;

                $query_update = 'UPDATE users SET 2fa_secret_code="' . $secret . '" WHERE id="' . $row['id'] . '";';
                $result_update = mysqli_query($conn, $query_update) or die('Query failed');
            }
        }
    }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel='stylesheet' href='../css/index.css' />
</head>
<body>
    <div class='content'>
        <?php
            // getting the QR code
            if($username != null && $generate_qr == true) {
                echo '<img class="center-horizontal" src="'.$google_auth->getURL($username, 'twofactor.teste.com', $secret).'"/>';
            } else if($generate_qr == false) { ?>
                <p class='subtitle'>Enter the code generated in your auth app</p>
                <input type='number' id='two_fa_code_auth' class='input' placeholder='code' />
                <input type='submit' id='check-code' value='Enviar' />
            <?php } ?>
    </div>

    <script>
        <?php if($generate_qr == false) { ?>
            document.querySelector('#check-code').onclick = () => {
                let code = document.querySelector('#two_fa_code_auth').value;

                <?php
                    $code =
                    $result = $google_auth->checkCode($secret, $code);
                ?>
                <?php

                ?>
            };
        <?php } ?>
    </script>
</body>
</html>